{% set name = "tiledb-cloud" %}
{% set version = "0.12.4" %}

package:
  name: tiledb-cloud-py
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a5917f337714d685278c4d0387930c4c8a5920d16337305f080083d61e043f4

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=42
    - wheel
    - setuptools-scm >=6
    - pip
  run:
    - python >=3.8
    - attrs >=21.4.0
    - certifi
    - cloudpickle >=1.4.1,<3
    - importlib-metadata
    - packaging
    - pandas >=1.2.4
    - pyarrow >=3.0.0
    - python-dateutil
    - six >=1.10
    - tblib >=1.7,<2.dev0
    - tiledb-py >=0.15.2
    - typing-extensions
    - urllib3 >=1.26

test:
  imports:
    - tiledb.cloud
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://docs.tiledb.com/cloud/tutorials/start-here
  summary: TileDB Cloud platform Python client
  license: MIT
  license_file: LICENSE
  doc_url: https://tiledb-inc.github.io/TileDB-Cloud-Py/
  dev_url: https://github.com/TileDB-Inc/TileDB-Cloud-Py

extra:
  recipe-maintainers:
    - shelnutt2
    - ihnorton
    - jdblischak
    - thetorpedodog
